version: '3.9'
services:
  auth:
    image: node:18
    depends_on:
      - users
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    command: sh -c "npm install && npm run dev"
    ports:
      - '3000:3000'
  users:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - './src/queries/initialise.sql:/docker-entrypoint-initdb.d/initialise.sql'
  swagger:
    image: swaggerapi/swagger-editor
    ports:
      - '8080:8080'
    volumes:
      - ./swagger:/tmp
    environment:
      - SWAGGER_FILE=/tmp/swagger.yaml
  pi-lib-auth-fe:
    image: lancerael/pi-lib-auth-fe
    ports:
      - '4173:4173'
